### ISSUE TITLE
Einweisung Lehrer

### ISSUE THREAD

**Issue by quotengrote** [Azubis-Dataport-Magdeburg/dp_schulserver#138]
- [x] Termin vereinbaren
- [x] VORHER Plan machen was erklärt werden soll

**Comment by quotengrote** [comment]
Wie siehts aus?

**Comment by quotengrote** [comment]
wird kombiniert mit #54

**Comment by DanielMueller1309** [comment]
termin steht drin
wegen besprechung zur vorstellung des ganzen würde ich für diese Woche noch einen Termin in dieser Woche einstellen damit wir eine kleine Produktpräsentation vorbereiten können bzw besprechen was alles genau erklärt werden soll.

**Comment by quotengrote** [comment]
stell mir einfach einen Termin rein

**Comment by quotengrote** [comment]
@DanielMueller1309 

- [ ] Neuen Termin vereinbaren

**Comment by quotengrote** [comment]
durchgeführt
