### ISSUE TITLE
KVM/Console Anzeige Bug

### ISSUE THREAD

**Issue by DanielMueller1309** [Azubis-Dataport-Magdeburg/dp_schulserver#167]
Nach dem Upgrade auf PVE7  und einem Neustart zeigt die Console des KVM "OUT OF RANGE" an

**Comment by MaxGoe** [comment]
könnte ein Display Error sein schau mal ob dir das weiterhilft 
https://forum.proxmox.com/threads/installing-proxmox-screen-issues-vga-on-hp-n54l.57051/
