### ISSUE TITLE
Mailfilter und Weiterleitung einrichten in gmail acc

### ISSUE THREAD

**Issue by DanielMueller1309** [Azubis-Dataport-Magdeburg/dp_schulserver#172]
Damit die Mails welche an die gmail gesendet werden auch an die azubis verteilt werden muss eine weiterleitung auf dem gmail acc eingerichtet werden.

**Comment by quotengrote** [comment]
Bis Mittwoch erledigen!

**Comment by DanielMueller1309** [comment]
@quotengrote @Kati-20DP @MaxGoe bitte einmal die kommende google mail wegen der weiterleitung bestätigen

**Comment by quotengrote** [comment]
Erledigt

**Comment by DanielMueller1309** [comment]
mailfilter eingerichtet
