### ISSUE TITLE
Einführung neuer Azubi 

### ISSUE THREAD

**Issue by MaxGoe** [Azubis-Dataport-Magdeburg/dp_schulserver#173]
- [x] Liste erstellen wer ihm was erklärt.
- [x] Terminfindung (Wann Einführung stattfindet, min 1 Tag vermutlich mehr)
- [x] Themen
- [ ] Anleitung für Installation fehlt?

**Comment by quotengrote** [comment]
@MaxGoe @Kati-20DP Ihr erstellt Termin + Vorbereitung

**Comment by Kati-20DP** [comment]
@quotengrote Möchtest du dann bei der Vorstellung mit dabei sein?

**Comment by Kati-20DP** [comment]
Themen:

[ ] Grund/ Funktion  
https://github.com/Azubis-Dataport-Magdeburg/dp_schulserver/blob/master/Gesamtdoku/Doku_Schueler.md

[ ] ProxMox Funktion
(Was es ist, warum verwenden, zeigen)

[ ] Aufbau 
(Welcher Storage, Wo und warum Angeschlossen, Fotos ggf. Besuch vor Ort)

**Comment by Kati-20DP** [comment]
@alle wir sollten mal absprechen, ob es noch weitere Themen gibt die wir mit vorstellen können.

**Comment by quotengrote** [comment]
Da wesentliche steht da, @DanielMueller1309 kann bei Bedarf ja noch seine Scripte vorstellen.

**Comment by quotengrote** [comment]
> @quotengrote Möchtest du dann bei der Vorstellung mit dabei sein?

Falls es zeitlich passt
