### ISSUE TITLE
lehrer in keepass umbenennen

### ISSUE THREAD

**Issue by DanielMueller1309** [Azubis-Dataport-Magdeburg/dp_schulserver#176]
lehrer00 in keepass zu lehrer machen da acc auf pve = leherer

**Comment by DanielMueller1309** [comment]
passwörter bleibem gleich

**Comment by DanielMueller1309** [comment]
lehrer von pve aus keepass entfernen

**Comment by quotengrote** [comment]
sind durchgestrichen
