### ISSUE TITLE
Vortrag Lehrer (offen)

### ISSUE THREAD

**Issue by quotengrote** [Azubis-Dataport-Magdeburg/dp_schulserver#59]
- [ ] Ansprechpartner
- [ ] aussichten wenn noch nicht fertig
- [ ] Entscheidung für SW/Hw, warumm was sind alternativen
- [ ] lessonslearned
- [ ] Organisatorisches
- [ ] Projekt
- [ ] Technisch Überblick
- [ ] was haben wir gebraucht
- [ ] was war gedacht
- [ ] was wollte die Schule
- [ ] wie technische Umsetzung

**Comment by DanielMueller1309** [comment]
Anbindung an aus dem ersten Lehrjahr vermittelten Unterrichts

Außerdem, wenn ich mich noch richtig an Plewes worte erinnere meinte er glaube wir sollten das ganze mit der klasse als Probelauf machen heißt wir müssten auch die technischen Grundlagen des Systems vermittelt und Erklärung wie man es bedient als Anwender

**Comment by MaxGoe** [comment]
Habt ihr den nicht schon gehalten und der Issue kann geschlossen werden?

**Comment by quotengrote** [comment]
Ja, haben wir gemacht.

**Comment by quotengrote** [comment]
Ach ne, das war der für die Schüler, der fehlt noch.

**Comment by MaxGoe** [comment]
Achso ok :D

**Comment by quotengrote** [comment]
klären @quotengrote @DanielMueller1309 in direkten Richten mit der BBS
