### ISSUE TITLE
Status 30.06.21

### ISSUE THREAD

**Issue by quotengrote** [Azubis-Dataport-Magdeburg/dp_schulserver#88]
# Übersicht

Am 05.06.21 war die Einweisung der Lehrer in das System geplant.
Vorher mussten wir noch einige Änderungen einpflegen(#75).
Danach hatten wir erneut einen Fehler in `multipath + lvm`(#57 )

Deswegen war ich heute vor Ort.

## Problem
Die DX80 ist mit zwei Pfaden an den Server angeschlossen(`sdb/sdc`).
Die beiden Devices werden mti Multipath zu einem (Device-Mapper)-Device(mpathb) zusammengefasst.
Auf `mpathb` wird dann ein PV erstellt, diese PV kommt in die VG `vg_mpathb` und die VG wird ProxMox als Storage zugewiesen.
Darauf werden dann die LVs für die einzelnen VMs erstellt.
Bis hierhin funktioniert alles.

Jetzt wird der Server neugestartet...
Danach bindet LVM das PV nicht mehr von `mpathb` ein, sondern von `sdb`.
Danach kommt es zum Fehler weil dann ein PV "mehrfach" am System hängt da nur ein Teil des multipath-devices angesprochen wird statt `mpathb`  

Mit der Lösung in #87 habe ich das beheben können, die VG wird jetzt immer aus `mpathb` eingelesen.
Die LVs werden aber weiterhin nur auf `sdb` eingelesen.
Fehler: ` WARNING: PV Q51XQY-AAHU-jacr-SrHb-1U8V-lE1N-XnbCFT prefers device /dev/sdb because device is used by LV.`

## Probierte Lösungen
- verschiedene LVM-Filter Kombinationen(#87 )
- Redeployment mit OS auf ZFS

## Workaround
Derzeit ist die DX80 nur mit einem Pfad(`sdb`) angeschlossen, damit läuft es wie es soll.
`DX80-->FC-->sdb-->PV-->VG-->LVs`
Die Rollen `lvm` und `multipath` sind NICHT ausgerollt.

# Weitere Probleme
<s>#89 </s>
<s>#90</s>
<s>#91</s>
<s>#92</s>
<s>#93</s>

# Infos
Für die Lehrer gibt es nur noch einen PAM-Account der auch auf PVE berechtigt ist.
Da derzeit kein `sudo` funktioniert muss das Root-Passwort eh übergeben werden. (kann mit #90 gelöst werden)

## Siehe auch
<s>#94</s>
<s>#87 </s>

**Comment by quotengrote** [comment]
Doing:
@DanielMueller1309 Scripte prüfen und Issues bearbeiten
@DanielMueller1309 Einweisung VORBEREITEN und Termin mit Herr P. vereinbaren

**Comment by quotengrote** [comment]
#96
#97
#98

**Comment by MaxGoe** [comment]
### Statusupdate 24.06.2021

Aufgrund von #96 waren wir heute wieder Vorort.

### Was haben wir gemacht?

- Wir haben PVE neu installiert und damit #96 behoben, d.h kein LVM und alles läuft über klassische Partitionen
- Im Zuge dessen natürlich auch die LVM Rolle entfernt, da wir diese nicht mehr benötigen
- Außerdem haben wir, weil wir Proxmox neu aufgesetzt haben, die Standardpakete neu installiert #90, 
sowie die ISO's hochgeladen und die Variablen angepasst #91

**Comment by quotengrote** [comment]
Folgende Probleme sind dabei (neu aufgetreten):
#116 

Sonstiges:
#117
#118
#119


Erledigt:
#96
#91
#90
#66

**Comment by quotengrote** [comment]
@DanielMueller1309 https://github.com/quotengrote/dp_schulserver/issues/88#issuecomment-858569652 Ist hier irgendwas passiert...?

**Comment by quotengrote** [comment]
Erledigt:

#129
#128
#126 
#133

+ VM-Install getestet 
+ Ping zwischen VMs getestet
+ WindowsVM auf ide umgestellt
+ VM+Poolzuweisung in template
